/* generated by Svelte v3.38.3 */
import { SvelteComponent, init, safe_not_equal } from '../web_modules/svelte/internal/index.mjs';

function get_description(articleBody, desc_length) {
	let desc_start = articleBody.indexOf("<p>");
	let desc_end = desc_start + desc_length;
	let desc = articleBody.substring(desc_start, Math.min(desc_end, articleBody.substring(0, desc_end).lastIndexOf(" "))) + "<span class=\"font-bold\"> ...</span></p>";
	return desc;
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;
export { get_description };