/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_component,
	claim_element,
	claim_space,
	claim_text,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	listen,
	mount_component,
	noop,
	run_all,
	safe_not_equal,
	set_data,
	set_input_value,
	set_style,
	space,
	text,
	transition_in,
	transition_out
} from '../web_modules/svelte/internal/index.mjs';

import Aside from './aside.js';

function create_else_block(ctx) {
	let t;

	return {
		c() {
			t = text(/*title*/ ctx[3]);
		},
		l(nodes) {
			t = claim_text(nodes, /*title*/ ctx[3]);
		},
		m(target, anchor) {
			insert(target, t, anchor);
		},
		p(ctx, dirty) {
			if (dirty & /*title*/ 8) set_data(t, /*title*/ ctx[3]);
		},
		d(detaching) {
			if (detaching) detach(t);
		}
	};
}

// (58:14) {#if tname.length > 1}
function create_if_block(ctx) {
	let span0;
	let t0_value = /*tname*/ ctx[11][0].toUpperCase() + "";
	let t0;
	let t1;
	let span1;
	let t2_value = /*tname*/ ctx[11][1].toUpperCase() + "";
	let t2;

	return {
		c() {
			span0 = element("span");
			t0 = text(t0_value);
			t1 = space();
			span1 = element("span");
			t2 = text(t2_value);
			this.h();
		},
		l(nodes) {
			span0 = claim_element(nodes, "SPAN", { class: true, style: true });
			var span0_nodes = children(span0);
			t0 = claim_text(span0_nodes, t0_value);
			t1 = claim_space(span0_nodes);
			span0_nodes.forEach(detach);
			span1 = claim_element(nodes, "SPAN", {});
			var span1_nodes = children(span1);
			t2 = claim_text(span1_nodes, t2_value);
			span1_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(span0, "class", "accent");
			set_style(span0, "opacity", "1");
		},
		m(target, anchor) {
			insert(target, span0, anchor);
			append(span0, t0);
			append(span0, t1);
			insert(target, span1, anchor);
			append(span1, t2);
		},
		p: noop,
		d(detaching) {
			if (detaching) detach(span0);
			if (detaching) detach(span1);
		}
	};
}

function create_fragment(ctx) {
	let section;
	let div0;
	let t0;
	let div16;
	let div15;
	let div13;
	let div12;
	let div11;
	let h2;
	let t1;
	let p;
	let t2;
	let t3;
	let form;
	let div3;
	let div1;
	let label0;
	let t4;
	let t5;
	let input0;
	let t6;
	let div2;
	let label1;
	let t7;
	let t8;
	let input1;
	let t9;
	let div5;
	let div4;
	let label2;
	let t10;
	let t11;
	let input2;
	let t12;
	let div7;
	let div6;
	let label3;
	let t13;
	let t14;
	let textarea;
	let t15;
	let div10;
	let div8;
	let button;
	let t16;
	let t17;
	let div9;
	let t18;
	let div14;
	let aside;
	let t19;
	let div17;
	let current;
	let mounted;
	let dispose;

	function select_block_type(ctx, dirty) {
		if (/*tname*/ ctx[11].length > 1) return create_if_block;
		return create_else_block;
	}

	let current_block_type = select_block_type(ctx, -1);
	let if_block = current_block_type(ctx);

	aside = new Aside({
			props: {
				allPosts: /*allPosts*/ ctx[0],
				catgPosts: /*catgPosts*/ ctx[1],
				tagsPosts: /*tagsPosts*/ ctx[2],
				socialLinks: /*socialLinks*/ ctx[9]
			}
		});

	return {
		c() {
			section = element("section");
			div0 = element("div");
			t0 = space();
			div16 = element("div");
			div15 = element("div");
			div13 = element("div");
			div12 = element("div");
			div11 = element("div");
			h2 = element("h2");
			if_block.c();
			t1 = space();
			p = element("p");
			t2 = text(/*articleBody*/ ctx[4]);
			t3 = space();
			form = element("form");
			div3 = element("div");
			div1 = element("div");
			label0 = element("label");
			t4 = text("First Name");
			t5 = space();
			input0 = element("input");
			t6 = space();
			div2 = element("div");
			label1 = element("label");
			t7 = text("Last Name");
			t8 = space();
			input1 = element("input");
			t9 = space();
			div5 = element("div");
			div4 = element("div");
			label2 = element("label");
			t10 = text("E-mail");
			t11 = space();
			input2 = element("input");
			t12 = space();
			div7 = element("div");
			div6 = element("div");
			label3 = element("label");
			t13 = text("Message");
			t14 = space();
			textarea = element("textarea");
			t15 = space();
			div10 = element("div");
			div8 = element("div");
			button = element("button");
			t16 = text("Send");
			t17 = space();
			div9 = element("div");
			t18 = space();
			div14 = element("div");
			create_component(aside.$$.fragment);
			t19 = space();
			div17 = element("div");
			this.h();
		},
		l(nodes) {
			section = claim_element(nodes, "SECTION", { class: true });
			var section_nodes = children(section);
			div0 = claim_element(section_nodes, "DIV", { class: true });
			children(div0).forEach(detach);
			t0 = claim_space(section_nodes);
			div16 = claim_element(section_nodes, "DIV", { class: true });
			var div16_nodes = children(div16);
			div15 = claim_element(div16_nodes, "DIV", { class: true });
			var div15_nodes = children(div15);
			div13 = claim_element(div15_nodes, "DIV", { class: true });
			var div13_nodes = children(div13);
			div12 = claim_element(div13_nodes, "DIV", { class: true });
			var div12_nodes = children(div12);
			div11 = claim_element(div12_nodes, "DIV", { class: true });
			var div11_nodes = children(div11);
			h2 = claim_element(div11_nodes, "H2", { class: true });
			var h2_nodes = children(h2);
			if_block.l(h2_nodes);
			h2_nodes.forEach(detach);
			t1 = claim_space(div11_nodes);
			p = claim_element(div11_nodes, "P", { class: true });
			var p_nodes = children(p);
			t2 = claim_text(p_nodes, /*articleBody*/ ctx[4]);
			p_nodes.forEach(detach);
			t3 = claim_space(div11_nodes);
			form = claim_element(div11_nodes, "FORM", { id: true, class: true });
			var form_nodes = children(form);
			div3 = claim_element(form_nodes, "DIV", { class: true });
			var div3_nodes = children(div3);
			div1 = claim_element(div3_nodes, "DIV", { class: true });
			var div1_nodes = children(div1);
			label0 = claim_element(div1_nodes, "LABEL", { class: true, for: true });
			var label0_nodes = children(label0);
			t4 = claim_text(label0_nodes, "First Name");
			label0_nodes.forEach(detach);
			t5 = claim_space(div1_nodes);

			input0 = claim_element(div1_nodes, "INPUT", {
				class: true,
				id: true,
				type: true,
				placeholder: true
			});

			div1_nodes.forEach(detach);
			t6 = claim_space(div3_nodes);
			div2 = claim_element(div3_nodes, "DIV", { class: true });
			var div2_nodes = children(div2);
			label1 = claim_element(div2_nodes, "LABEL", { class: true, for: true });
			var label1_nodes = children(label1);
			t7 = claim_text(label1_nodes, "Last Name");
			label1_nodes.forEach(detach);
			t8 = claim_space(div2_nodes);

			input1 = claim_element(div2_nodes, "INPUT", {
				class: true,
				id: true,
				type: true,
				placeholder: true
			});

			div2_nodes.forEach(detach);
			div3_nodes.forEach(detach);
			t9 = claim_space(form_nodes);
			div5 = claim_element(form_nodes, "DIV", { class: true });
			var div5_nodes = children(div5);
			div4 = claim_element(div5_nodes, "DIV", { class: true });
			var div4_nodes = children(div4);
			label2 = claim_element(div4_nodes, "LABEL", { class: true, for: true });
			var label2_nodes = children(label2);
			t10 = claim_text(label2_nodes, "E-mail");
			label2_nodes.forEach(detach);
			t11 = claim_space(div4_nodes);

			input2 = claim_element(div4_nodes, "INPUT", {
				class: true,
				id: true,
				type: true,
				placeholder: true
			});

			div4_nodes.forEach(detach);
			div5_nodes.forEach(detach);
			t12 = claim_space(form_nodes);
			div7 = claim_element(form_nodes, "DIV", { class: true });
			var div7_nodes = children(div7);
			div6 = claim_element(div7_nodes, "DIV", { class: true });
			var div6_nodes = children(div6);
			label3 = claim_element(div6_nodes, "LABEL", { class: true, for: true });
			var label3_nodes = children(label3);
			t13 = claim_text(label3_nodes, "Message");
			label3_nodes.forEach(detach);
			t14 = claim_space(div6_nodes);
			textarea = claim_element(div6_nodes, "TEXTAREA", { class: true, id: true, placeholder: true });
			children(textarea).forEach(detach);
			div6_nodes.forEach(detach);
			div7_nodes.forEach(detach);
			t15 = claim_space(form_nodes);
			div10 = claim_element(form_nodes, "DIV", { class: true });
			var div10_nodes = children(div10);
			div8 = claim_element(div10_nodes, "DIV", { class: true });
			var div8_nodes = children(div8);
			button = claim_element(div8_nodes, "BUTTON", { class: true, id: true, type: true });
			var button_nodes = children(button);
			t16 = claim_text(button_nodes, "Send");
			button_nodes.forEach(detach);
			div8_nodes.forEach(detach);
			t17 = claim_space(div10_nodes);
			div9 = claim_element(div10_nodes, "DIV", { class: true });
			children(div9).forEach(detach);
			div10_nodes.forEach(detach);
			form_nodes.forEach(detach);
			div11_nodes.forEach(detach);
			div12_nodes.forEach(detach);
			div13_nodes.forEach(detach);
			t18 = claim_space(div15_nodes);
			div14 = claim_element(div15_nodes, "DIV", { class: true });
			var div14_nodes = children(div14);
			claim_component(aside.$$.fragment, div14_nodes);
			div14_nodes.forEach(detach);
			div15_nodes.forEach(detach);
			div16_nodes.forEach(detach);
			t19 = claim_space(section_nodes);
			div17 = claim_element(section_nodes, "DIV", { class: true });
			children(div17).forEach(detach);
			section_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(div0, "class", "w-0 md:w-1/12 xl:w-2/12");
			attr(h2, "class", "header text-xl md:text-2xl lg:text-3xl my-6");
			attr(p, "class", "mb-10");
			attr(label0, "class", "block uppercase tracking-wide header mb-2");
			attr(label0, "for", "grid-first-name");
			attr(input0, "class", "appearance-none block w-full bg-gray-100 text-gray-700 border border-gray-400 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white");
			attr(input0, "id", "grid-first-name");
			attr(input0, "type", "text");
			attr(input0, "placeholder", "Jane");
			attr(div1, "class", "w-full md:w-1/2 px-3 mb-6 md:mb-0");
			attr(label1, "class", "block uppercase tracking-wide header mb-2");
			attr(label1, "for", "grid-last-name");
			attr(input1, "class", "appearance-none block w-full bg-gray-100 text-gray-700 border border-gray-400 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white");
			attr(input1, "id", "grid-last-name");
			attr(input1, "type", "text");
			attr(input1, "placeholder", "Doe");
			attr(div2, "class", "w-full md:w-1/2 px-3");
			attr(div3, "class", "flex flex-wrap -mx-3 mb-6");
			attr(label2, "class", "block uppercase tracking-wide header mb-2");
			attr(label2, "for", "grid-password");
			attr(input2, "class", "appearance-none block w-full bg-gray-100 text-gray-700 border border-gray-400 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white");
			attr(input2, "id", "email");
			attr(input2, "type", "email");
			attr(input2, "placeholder", "Jane.Doe@example.net");
			input2.required = true;
			attr(div4, "class", "w-full px-3");
			attr(div5, "class", "flex flex-wrap -mx-3 mb-6");
			attr(label3, "class", "block uppercase tracking-wide header mb-2");
			attr(label3, "for", "grid-password");
			attr(textarea, "class", " no-resize appearance-none block w-full bg-gray-100 text-gray-700 border border-gray-400 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white h-48 resize-none");
			attr(textarea, "id", "message");
			attr(textarea, "placeholder", "Write something here...");
			attr(div6, "class", "w-full px-3");
			attr(div7, "class", "flex flex-wrap -mx-3 mb-6");
			attr(button, "class", "btn-outline mb-6 px-4 rounded");
			attr(button, "id", "submit");
			attr(button, "type", "submit");
			attr(div8, "class", "md:w-1/3");
			attr(div9, "class", "md:w-2/3");
			attr(div10, "class", "md:flex md:items-center");
			attr(form, "id", "contactform");
			attr(form, "class", "w-full max-w-lg");
			attr(div11, "class", "mx-2 md:mx-6 mb-2 md:mb-3 my-1");
			attr(div12, "class", "rounded-xl overflow-hidden shadow-md bg-secondary");
			attr(div13, "class", "w-full md:w-9/12 mb-lg-0 px-0 sm:pr-10");
			attr(div14, "class", "w-full md:w-3/12 mb-lg-0 px-0");
			attr(div15, "class", "row md:flex md:flex-wrap");
			attr(div16, "class", "w-full md:w-10/12 xl:w-8/12 px-2 md:px-0");
			attr(div17, "class", "w-0 md:w-1/12 xl:w-2/12");
			attr(section, "class", "section flex flex-wrap items-center justify-between");
		},
		m(target, anchor) {
			insert(target, section, anchor);
			append(section, div0);
			append(section, t0);
			append(section, div16);
			append(div16, div15);
			append(div15, div13);
			append(div13, div12);
			append(div12, div11);
			append(div11, h2);
			if_block.m(h2, null);
			append(div11, t1);
			append(div11, p);
			append(p, t2);
			append(div11, t3);
			append(div11, form);
			append(form, div3);
			append(div3, div1);
			append(div1, label0);
			append(label0, t4);
			append(div1, t5);
			append(div1, input0);
			set_input_value(input0, /*nameFrst*/ ctx[6]);
			append(div3, t6);
			append(div3, div2);
			append(div2, label1);
			append(label1, t7);
			append(div2, t8);
			append(div2, input1);
			set_input_value(input1, /*nameLast*/ ctx[7]);
			append(form, t9);
			append(form, div5);
			append(div5, div4);
			append(div4, label2);
			append(label2, t10);
			append(div4, t11);
			append(div4, input2);
			set_input_value(input2, /*addrFrom*/ ctx[5]);
			append(form, t12);
			append(form, div7);
			append(div7, div6);
			append(div6, label3);
			append(label3, t13);
			append(div6, t14);
			append(div6, textarea);
			set_input_value(textarea, /*msgBody*/ ctx[8]);
			append(form, t15);
			append(form, div10);
			append(div10, div8);
			append(div8, button);
			append(button, t16);
			append(div10, t17);
			append(div10, div9);
			append(div15, t18);
			append(div15, div14);
			mount_component(aside, div14, null);
			append(section, t19);
			append(section, div17);
			current = true;

			if (!mounted) {
				dispose = [
					listen(input0, "input", /*input0_input_handler*/ ctx[13]),
					listen(input1, "input", /*input1_input_handler*/ ctx[14]),
					listen(input2, "input", /*input2_input_handler*/ ctx[15]),
					listen(textarea, "input", /*textarea_input_handler*/ ctx[16]),
					listen(button, "click", /*contactSend*/ ctx[10])
				];

				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if_block.p(ctx, dirty);
			if (!current || dirty & /*articleBody*/ 16) set_data(t2, /*articleBody*/ ctx[4]);

			if (dirty & /*nameFrst*/ 64 && input0.value !== /*nameFrst*/ ctx[6]) {
				set_input_value(input0, /*nameFrst*/ ctx[6]);
			}

			if (dirty & /*nameLast*/ 128 && input1.value !== /*nameLast*/ ctx[7]) {
				set_input_value(input1, /*nameLast*/ ctx[7]);
			}

			if (dirty & /*addrFrom*/ 32 && input2.value !== /*addrFrom*/ ctx[5]) {
				set_input_value(input2, /*addrFrom*/ ctx[5]);
			}

			if (dirty & /*msgBody*/ 256) {
				set_input_value(textarea, /*msgBody*/ ctx[8]);
			}

			const aside_changes = {};
			if (dirty & /*allPosts*/ 1) aside_changes.allPosts = /*allPosts*/ ctx[0];
			if (dirty & /*catgPosts*/ 2) aside_changes.catgPosts = /*catgPosts*/ ctx[1];
			if (dirty & /*tagsPosts*/ 4) aside_changes.tagsPosts = /*tagsPosts*/ ctx[2];
			aside.$set(aside_changes);
		},
		i(local) {
			if (current) return;
			transition_in(aside.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(aside.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(section);
			if_block.d();
			destroy_component(aside);
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { idxContent } = $$props,
		{ allPosts } = $$props,
		{ catgPosts } = $$props,
		{ tagsPosts } = $$props;

	let { title } = $$props, { articleBody } = $$props;
	let socialLinks = idxContent.socialLinks;
	let addrFrom = "";
	let nameFrst = "";
	let nameLast = "";
	let subject = idxContent.name;
	let msgBody = "";

	// TODO: complete serverless function for sending contact request
	function contactSend(addrFrom, nameFrst, nameLast, msgBody) {
		const msgData = JSON.stringify({
			addr: addrFrom,
			frst: nameFrst,
			last: nameLast,
			subj: subject,
			body: msgBody
		});

		// console.log(msgData);
		// Setup XML connection request
		const API_URL = "https://";

		const xhr = new XMLHttpRequest();
		xhr.withCredentials = true;

		xhr.addEventListener("readystatechange", function () {
			if (this.readyState === this.DONE) {
				console.log(this.responseText);
			}
		});

		// Send message
		xhr.open("POST", API_URL + "mail/send");

		xhr.setRequestHeader("content-type", "application/json");
		xhr.send(msgData);
	}

	let tname = title.split(" ");

	function input0_input_handler() {
		nameFrst = this.value;
		$$invalidate(6, nameFrst);
	}

	function input1_input_handler() {
		nameLast = this.value;
		$$invalidate(7, nameLast);
	}

	function input2_input_handler() {
		addrFrom = this.value;
		$$invalidate(5, addrFrom);
	}

	function textarea_input_handler() {
		msgBody = this.value;
		$$invalidate(8, msgBody);
	}

	$$self.$$set = $$props => {
		if ("idxContent" in $$props) $$invalidate(12, idxContent = $$props.idxContent);
		if ("allPosts" in $$props) $$invalidate(0, allPosts = $$props.allPosts);
		if ("catgPosts" in $$props) $$invalidate(1, catgPosts = $$props.catgPosts);
		if ("tagsPosts" in $$props) $$invalidate(2, tagsPosts = $$props.tagsPosts);
		if ("title" in $$props) $$invalidate(3, title = $$props.title);
		if ("articleBody" in $$props) $$invalidate(4, articleBody = $$props.articleBody);
	};

	return [
		allPosts,
		catgPosts,
		tagsPosts,
		title,
		articleBody,
		addrFrom,
		nameFrst,
		nameLast,
		msgBody,
		socialLinks,
		contactSend,
		tname,
		idxContent,
		input0_input_handler,
		input1_input_handler,
		input2_input_handler,
		textarea_input_handler
	];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			idxContent: 12,
			allPosts: 0,
			catgPosts: 1,
			tagsPosts: 2,
			title: 3,
			articleBody: 4
		});
	}
}

export default Component;